# Generated by Django 3.2.7 on 2021-10-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
                ('postal_address', models.CharField(max_length=30)),
                ('city', models.CharField(default='Nairobi', editable=False, max_length=30)),
                ('servicies', models.CharField(max_length=30)),
                ('comments', models.CharField(max_length=500)),
            ],
        ),
    ]
