# Generated by Django 3.2.7 on 2021-10-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_alter_bookings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
