# Generated by Django 3.2.7 on 2021-10-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_bookings_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('sname', models.CharField(max_length=30)),
                ('tname', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=15)),
                ('id_no', models.CharField(max_length=15)),
                ('dobdate', models.DateTimeField(auto_now_add=True)),
                ('home_town', models.CharField(default='Nairobi', editable=False, max_length=30)),
                ('occupation', models.CharField(max_length=30)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
